@extends('layouts.app')

@section('title', 'Invoice details')
@section('page_title', 'Billing Invoice')

@section('content')
<div class="row">
    <!-- Invoice details Panel -->
    <div class="col-lg-8 mb-4">
        <div class="card card-custom mb-4">
            <div class="card-header bg-transparent border-0 pt-4 px-4 d-flex justify-content-between align-items-center">
                <h5 class="fw-bold m-0"><i class="fa-solid fa-file-invoice text-primary me-2"></i>Invoice: {{ $invoice->invoice_no }}</h5>
                <div>
                    <a href="{{ route('invoices.pdf', $invoice->id) }}" class="btn btn-outline-success btn-sm me-2">
                        <i class="fa-solid fa-file-pdf me-1"></i> Export PDF
                    </a>
                    @if($invoice->balance > 0)
                        @can('payments.create')
                        <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#collectPaymentModal">
                            <i class="fa-solid fa-credit-card me-1"></i> Record Payment
                        </button>
                        @endcan
                    @endif
                </div>
            </div>
            <div class="card-body px-4">
                <!-- Meta Grid -->
                <div class="row g-3 mb-4">
                    <div class="col-md-6">
                        <span class="text-secondary small d-block mb-1">Customer / Client</span>
                        <h6 class="fw-bold"><a href="{{ route('customers.show', $invoice->customer_id) }}" class="text-decoration-none">{{ $invoice->customer->company_name }}</a></h6>
                    </div>
                    <div class="col-md-3 col-6">
                        <span class="text-secondary small d-block mb-1">Invoice Date</span>
                        <h6>{{ $invoice->invoice_date->format('Y-m-d') }}</h6>
                    </div>
                    <div class="col-md-3 col-6">
                        <span class="text-secondary small d-block mb-1">Due Date</span>
                        @php
                            $isOverdue = $invoice->due_date->isPast() && $invoice->balance > 0;
                        @endphp
                        <h6 class="fw-bold {{ $isOverdue ? 'text-danger' : '' }}">{{ $invoice->due_date->format('Y-m-d') }}</h6>
                    </div>
                    
                    <hr class="text-light-hover my-2">

                    <div class="col-md-3 col-6">
                        <span class="text-secondary small d-block mb-1">Invoice Status</span>
                        @php
                            $invBadge = 'bg-secondary';
                            if ($invoice->status === 'Paid') $invBadge = 'bg-success';
                            elseif ($invoice->status === 'Partial') $invBadge = 'bg-info text-white';
                            elseif ($invoice->status === 'Sent') $invBadge = 'bg-primary';
                            elseif ($invoice->status === 'Overdue') $invBadge = 'bg-danger';
                        @endphp
                        <span class="badge {{ $invBadge }}">{{ $invoice->status }}</span>
                    </div>
                    <div class="col-md-3 col-6">
                        <span class="text-secondary small d-block mb-1">Outstanding Balance</span>
                        <h6 class="fw-bold {{ $invoice->balance > 0 ? 'text-danger' : 'text-success' }}">₹{{ number_format($invoice->balance, 2) }}</h6>
                    </div>
                    <div class="col-md-6">
                        <span class="text-secondary small d-block mb-1">Generated By</span>
                        <span class="text-dark small"><i class="fa-regular fa-user me-1"></i>{{ $invoice->creator->name ?? 'System' }}</span>
                    </div>
                </div>

                <!-- Line Items Table -->
                <h6 class="fw-bold text-secondary mb-3">Line Items</h6>
                <div class="table-responsive mb-4">
                    <table class="table table-hover align-middle border-top">
                        <thead>
                            <tr class="table-light">
                                <th>Description</th>
                                <th style="width: 80px;" class="text-center">Qty</th>
                                <th style="width: 150px;" class="text-end">Rate (₹)</th>
                                <th style="width: 150px;" class="text-end">Amount (₹)</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($invoice->invoiceItems as $item)
                                <tr>
                                    <td>
                                        {{ $item->description }}
                                        @if($item->customerService)
                                            <span class="small d-block text-secondary">Linked Service: <a href="{{ route('customer-services.show', $item->customer_service_id) }}" class="text-decoration-none">{{ $item->customerService->service_name }}</a></span>
                                        @endif
                                    </td>
                                    <td class="text-center">{{ $item->qty }}</td>
                                    <td class="text-end">₹{{ number_format($item->rate, 2) }}</td>
                                    <td class="text-end fw-semibold text-dark">₹{{ number_format($item->amount, 2) }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>

                <!-- Notes -->
                @if($invoice->notes)
                <div class="mt-4">
                    <span class="text-secondary small d-block mb-2">Notes / Special Instructions</span>
                    <div class="p-3 bg-light rounded text-secondary" style="font-size: 0.9rem;">
                        {!! nl2br(e($invoice->notes)) !!}
                    </div>
                </div>
                @endif
            </div>
        </div>

        <!-- Payments Collected List -->
        <div class="card card-custom">
            <div class="card-header bg-transparent border-0 pt-4 px-4">
                <h5 class="fw-bold m-0"><i class="fa-solid fa-wallet text-success me-2"></i>Payments Collected</h5>
            </div>
            <div class="card-body px-4 pb-4">
                <div class="table-responsive">
                    <table class="table table-hover align-middle">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Method</th>
                                <th>Transaction No</th>
                                <th>Amount (₹)</th>
                                <th>Receipt</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($invoice->payments as $payment)
                                <tr>
                                    <td>{{ $payment->payment_date->format('Y-m-d') }}</td>
                                    <td><span class="badge bg-light text-dark border">{{ $payment->payment_method }}</span></td>
                                    <td><code>{{ $payment->transaction_no ?? '-' }}</code></td>
                                    <td class="fw-bold text-success">+₹{{ number_format($payment->amount, 2) }}</td>
                                    <td>
                                        @if($payment->receipt)
                                            <a href="{{ route('receipts.show', $payment->receipt->id) }}" class="btn btn-sm btn-outline-success" title="View Receipt PDF"><i class="fa-solid fa-receipt"></i></a>
                                        @else
                                            -
                                        @endif
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="5" class="text-center py-3 text-secondary">No payment transactions logged against this invoice yet.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Calculations Sidebar -->
    <div class="col-lg-4">
        <div class="card card-custom mb-4 bg-light border-0">
            <div class="card-body p-4">
                <h5 class="fw-bold text-dark mb-4">Invoice Summary</h5>
                
                <div class="d-flex justify-content-between mb-2">
                    <span class="text-secondary">Subtotal:</span>
                    <span class="fw-semibold">₹{{ number_format($invoice->subtotal, 2) }}</span>
                </div>
                <div class="d-flex justify-content-between mb-2">
                    <span class="text-secondary text-danger">Discount:</span>
                    <span class="fw-semibold text-danger">-₹{{ number_format($invoice->discount, 2) }}</span>
                </div>
                <div class="d-flex justify-content-between mb-2">
                    <span class="text-secondary">Tax (GST):</span>
                    <span class="fw-semibold">₹{{ number_format($invoice->tax, 2) }}</span>
                </div>
                
                <hr class="text-light-hover my-3">
                
                <div class="d-flex justify-content-between mb-2">
                    <span class="fw-bold text-dark">Total Invoice:</span>
                    <span class="fw-bold text-dark">₹{{ number_format($invoice->total, 2) }}</span>
                </div>
                <div class="d-flex justify-content-between mb-0">
                    <span class="fw-bold text-danger">Remaining Balance:</span>
                    <span class="fw-bold text-danger">₹{{ number_format($invoice->balance, 2) }}</span>
                </div>
            </div>
        </div>

        <!-- Danger Zone Delete -->
        @can('invoices.delete')
            @if($invoice->payments->isEmpty())
                <div class="card card-custom border-danger-subtle bg-danger-subtle mb-4">
                    <div class="card-body p-4">
                        <h6 class="fw-bold text-danger mb-2">Danger Zone</h6>
                        <p class="small text-secondary mb-3">Removing this invoice is permanent. This action is disabled if payment receipts are already generated.</p>
                        <form action="{{ route('invoices.destroy', $invoice->id) }}" method="POST" class="delete-form">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger btn-sm w-100 btn-delete">
                                <i class="fa-regular fa-trash-can me-1"></i> Delete Invoice
                            </button>
                        </form>
                    </div>
                </div>
            @endif
        @endcan
    </div>
</div>

<!-- Record Payment Modal -->
@if($invoice->balance > 0)
<div class="modal fade" id="collectPaymentModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <form action="{{ route('payments.store') }}" method="POST">
            @csrf
            <input type="hidden" name="invoice_id" value="{{ $invoice->id }}">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title fw-bold">Record Invoice Payment</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="amount" class="form-label">Payment Amount (₹) <span class="text-danger">*</span></label>
                        <div class="input-group">
                            <span class="input-group-text">₹</span>
                            <input type="number" step="0.01" min="0.01" max="{{ $invoice->balance }}" 
                                   class="form-control" id="amount" name="amount" value="{{ $invoice->balance }}" required>
                        </div>
                        <div class="form-text">Outstanding Balance: ₹{{ number_format($invoice->balance, 2) }}</div>
                    </div>
                    
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <label for="payment_method" class="form-label">Method <span class="text-danger">*</span></label>
                            <select class="form-select" id="payment_method" name="payment_method" required>
                                <option value="UPI">UPI</option>
                                <option value="Bank Transfer">Bank Transfer</option>
                                <option value="Cash">Cash</option>
                                <option value="Cheque">Cheque</option>
                                <option value="Razorpay">Razorpay</option>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <label for="transaction_no" class="form-label">Transaction No / Ref</label>
                            <input type="text" class="form-control" id="transaction_no" name="transaction_no" placeholder="e.g. TXN987654">
                        </div>
                    </div>
                    
                    <div class="mb-0">
                        <label for="remarks" class="form-label">Internal Remarks</label>
                        <textarea class="form-control" id="remarks" name="remarks" rows="2" placeholder="Cheque clearances dates, bank name, etc."></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-bs-toggle="modal">Cancel</button>
                    <button type="submit" class="btn btn-success">Record Collection</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endif
@endsection

@section('scripts')
<script>
    $(document).ready(function() {
        // SweetAlert Delete Confirmation
        $(document).on('click', '.btn-delete', function(e) {
            e.preventDefault();
            var form = $(this).closest('form');
            
            Swal.fire({
                title: 'Are you sure?',
                text: "Deleting this invoice record is permanent.",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#ef4444',
                cancelButtonColor: '#64748b',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    form.submit();
                }
            });
        });
    });
</script>
@endsection
